// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-fA04G01Jec01XZ3CfFl67FLIhHPYDnU',
    appId: '1:958309319911:web:acae757dd449e05023ce42',
    messagingSenderId: '958309319911',
    projectId: 'music-app-71d51',
    authDomain: 'music-app-71d51.firebaseapp.com',
    storageBucket: 'music-app-71d51.appspot.com',
    measurementId: 'G-9VZ78M8072',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpf4pFUgXq5k4qnTTkk32AoiI2t_ld5wc',
    appId: '1:958309319911:android:b28b50c44313300a23ce42',
    messagingSenderId: '958309319911',
    projectId: 'music-app-71d51',
    storageBucket: 'music-app-71d51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArkLXf7-_DQzFXzzkkQ0DkbbvjF4MZxgM',
    appId: '1:958309319911:ios:2861fe0825e0c68e23ce42',
    messagingSenderId: '958309319911',
    projectId: 'music-app-71d51',
    storageBucket: 'music-app-71d51.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArkLXf7-_DQzFXzzkkQ0DkbbvjF4MZxgM',
    appId: '1:958309319911:ios:8c7a8a97c729396e23ce42',
    messagingSenderId: '958309319911',
    projectId: 'music-app-71d51',
    storageBucket: 'music-app-71d51.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
